1. Write a Python NumPy program to create a 3x3 identity matrix.

In [ ]:
import numpy as np

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Write a Python NumPy program to create a 4x4 matrix with values ranging from 2 to 10

In [ ]:
import numpy as np

matrix = np.arange(2, 18).reshape(4, 4)

print(matrix)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


3. Program to create a user-defined package
Step 1 — Folder Structure
Step 2 — ops.py
Step 3 — Main Program

In [ ]:
import os
os.makedirs("mypackage", exist_ok=True)

In [ ]:
open("mypackage/__init__.py", "w").close()

In [ ]:
%%writefile mypackage/ops.py

def add(a, b):
    return a + b

def multiply(a, b):
    return a * b

Overwriting mypackage/ops.py


In [ ]:
from mypackage import ops

print("Addition:", ops.add(5, 3))
print("Multiplication:", ops.multiply(5, 3))

Addition: 8
Multiplication: 15


In [ ]:
import numpy

a = numpy.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
from mypackage.ops import add

print(add(3, 2))

5
